### ISSUE TITLE
Pytwain + Flask server + Windows Service

### ISSUE THREAD

**Issue by lberselli-energee3** [denisenkom/pytwain#39]
For my thesis project, I intended to create a web application in Angular that allows access to a scanner via a Flask server. The server works, and I can access the scanner through the web page. However, I later thought of converting the server into a Windows Service so that it automatically starts when I boot the computer. While most Flask functionalities work well as a service, the scanner functionality stalls at the "open_source()" call, preventing the webpage from progressing and the scanner device selection window from opening. Have you encountered a similar issue, or is this specific to my situation?

**Comment by denisenkom** [comment]
According to this https://learn.microsoft.com/en-us/windows/win32/services/interactive-services Windows service cannot have a GUI.  This article also has some options that you can explore.

Another option could be to not show GUI in your server application, e.g. when calling open_source pass source ID so that it does not present a GUI.

**Comment by lberselli-energee3** [comment]
Thank you for the advice! I would have never figured it out.
